"""Update DICOMMetadataLog ID to UUID

Revision ID: 254fedb6ddd3
Revises: a6405888bbcc
Create Date: 2025-07-31 20:12:59.702560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254fedb6ddd3'
down_revision = 'a6405888bbcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
