"""Fix UUID type for metadata_logs.id

Revision ID: 6111d65805ac
Revises: 254fedb6ddd3
Create Date: 2025-07-31 20:20:09.381281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6111d65805ac'
down_revision = '254fedb6ddd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
