"""Add id column to dicom_metadata_logs

Revision ID: a6405888bbcc
Revises: 62f4809f6ba3
Create Date: 2025-07-31 19:20:45.127005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6405888bbcc'
down_revision = '62f4809f6ba3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
